@host = http://localhost:8081/user
@apj = application/json

### 注册
POST {{host}}/account
Content-Type: {{apj}}

{
    "nickname":"鱼尾",
    "email":"yuweijiubayiqi@163.com",
    "password":"aaaaaa"
}

### 注册
POST {{host}}/account
Content-Type: {{apj}}

{
    "nickname":"liba2",
    "email":"liba2@163.com",
    "password":"aaaaaa"
}

### 登录
GET {{host}}/account/SI7jHobAuSoA9Abu1fRE
Content-Type: {{apj}}

{
    "email":"liba2@163.com",
    "password":"aaaaaa"
}

### 提交标签
POST {{host}}/account/tags/SI7jHobAuSoA9Abu1fRE HTTP/1.1
Content-Type: {{apj}}

{
    "email":"liba2@163.com",
    "school":"南阳理工学院",
    "interesttags":["1","2","3","4","5","6"]
}