@host = http://localhost:8081/user
@apj = application/json

###
POST {{host}}/account
Content-Type: {{apj}}

{
    "nickname":"鱼尾",
    "email":"yuweijiubayiqi@163.com",
    "password":"aaaaaa"
}

###
POST {{host}}/account
Content-Type: {{apj}}

{
    "nickname":"",
    "email":"wuyaziyuwei@163.com",
    "password":"aaaaaa"
}
